function Begin()
  while true do
    wait(2)
    object.sound.Play()
    wait(1)
    object.sound.Play()
    wait(0.2)
    object.sound.Play()
    wait(0.5)
    object.sound.Play()
    wait(5)
    object.sound.Play()
    wait(2)
    object.sound.Play()
    wait(0.2)
    object.sound.Play()
    wait(0.5)
    object.sound.Play()
    wait(3)
    object.sound.Play()
    wait(0.5)
    object.sound.Play()
  end
end